name: Build VENTUS
env:
  LLVM: llvm-project
  RODINIA: gpu-rodinia
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # Runs at 2am everyday
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout pocl
      uses: actions/checkout@v4
      with:
        path: pocl

    - name: Checkout llvm-ventus
      uses: actions/checkout@v4
      with:
        repository: THU-DSP-LAB/llvm-project
        path: llvm-project

    - name: Checkout ocl-icd
      uses: actions/checkout@v4
      with:
        repository: OCL-dev/ocl-icd
        path: ocl-icd

    - name: Checkout driver
      uses: actions/checkout@v4
      with:
        repository: THU-DSP-LAB/ventus-driver
        path: ventus-driver

    - name: Checkout spike
      uses: actions/checkout@v4
      with:
        repository: THU-DSP-LAB/ventus-gpgpu-isa-simulator
        path: ventus-gpgpu-isa-simulator

    - name: Checkout rodinia
      uses: actions/checkout@v4
      with:
        repository: THU-DSP-LAB/gpu-rodinia
        path: gpu-rodinia

    - name: Use node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        registry-url: 'https://registry.npmjs.org'

    - name: Install ninja
      uses: llvm/actions/install-ninja@main

    - name: Install Other needed packages
      run: |
        sudo apt-get install -y \
        device-tree-compiler \
        bsdmainutils \
        ccache

    - name: Download data
      run: |
        wget -P ${{github.workspace}}/$RODINIA -c https://www.dropbox.com/s/cc6cozpboht3mtu/rodinia-3.1-data.tar.gz
        tar -zxvf ${{github.workspace}}/$RODINIA/rodinia-3.1-data.tar.gz -C ${{github.workspace}}/$RODINIA
        mv ${{github.workspace}}/$RODINIA/rodinia-data/* ${{github.workspace}}/$RODINIA/data/
        rm ${{github.workspace}}/$RODINIA/rodinia-* -rf
        cd ${{github.workspace}}/$LLVM

    - name: Start building llvm-ventus
      shell: bash
      run: |
        bash ${{github.workspace}}/$LLVM/build-ventus.sh --build llvm

    - name: Start building ocl-icd
      shell: bash
      run: |
        bash ${{github.workspace}}/$LLVM/build-ventus.sh --build ocl-icd

    - name: Start building libclc
      shell: bash
      run: |
        bash ${{github.workspace}}/$LLVM/build-ventus.sh --build libclc

    - name: Start building spike
      shell: bash
      run: |
        bash ${{github.workspace}}/$LLVM/build-ventus.sh --build spike

    - name: Start building driver
      shell: bash
      run: |
        bash ${{github.workspace}}/$LLVM/build-ventus.sh --build driver

    - name: Start building pocl
      shell: bash
      run: |
        bash ${{github.workspace}}/$LLVM/build-ventus.sh --build pocl

    - name: Start testing gpu-rodinia
      shell: bash
      run: |
         bash ${{github.workspace}}/$LLVM/build-ventus.sh --build rodinia

    - name: Start testing pocl
      shell: bash
      run: |
         bash ${{github.workspace}}/$LLVM/build-ventus.sh --build test-pocl

    - name: Start ISA simulation test
      run: |
        # Later need to add test files and test script for testing
        echo "Test files and scripts will be added later"
